import sys
import serial
import threading
import time
import sqlite3
from SatdbTable import   Ui_DialogSat

sys._excepthook = sys.excepthook
def my_exception_hook(exctype, value, traceback):
    print(exctype, value, traceback)
    sys._excepthook(exctype, value, traceback)
    sys.exit(1)
sys.excepthook = my_exception_hook

stop_threads = False

from PyQt5 import QtCore, QtGui, QtWidgets
class Ui_MainWindow(object):
    global connected
    def SerialDataCheck(self):
            print(" port opened")
            port = "\\\\.\\COM32"
            baud = 38400
            serial_port = serial.Serial(port,baud,parity=serial.PARITY_NONE,stopbits=serial.STOPBITS_ONE,bytesize=serial.EIGHTBITS, timeout=0)

            def handle_data(data):
                x = 1
                #y = data, end=''
                #print(data, end='')
                #print(data)
                #self.CurrentElevationText.setText()
                # print(data)

            def read_from_port(serial_port):
                connected = True
                while connected:
                    print(connected)
                    serial_port.write(b"dfsdgsfgfgsdg")


                    while True:
                        print(stop_threads)
                        if stop_threads:
                                break

                        while serial_port.in_waiting:
                                if stop_threads:
                                        break
                                a = serial_port.readline().decode()
                                m = a.strip("C,")
                                n = m.strip("\r\n")
                                l = n.strip(' ')
                                s = l.split(",")
                                if len(s) == 4:
                                        #print(s[1], s[2], s[3])
                                        self.CurrentElevationText.setText(str(s[1]))
                                        self.CurrentAzimuthText.setText(str(s[2]))
                                        self.CurrentPolarizationText.setText(str(s[3]))
                                else:
                                        break

                                '''print("azimuth is :" + azimuth)
                                print("elevation is :" + elevation)
                                print("polarization is :" + polarization)
                                self.CurrentElevationText.setText(str(elevation))
                                self.CurrentAzimuthText.setText(str(azimuth))
                                self.CurrentPolarizationText.setText(str(polarization))'''
                                connected = False

            thread = threading.Thread(target=read_from_port, args=(serial_port,))
            thread.start()
            time.sleep(1)


    def ShutDownCheck(self):
        global stop_threads
        stop_threads = True

        if stop_threads == True:
            sys.exit()

    def ThreadStop(self):
        print("gps clicked")
        global stop_threads
        stop_threads = True

    def opendb(self):
            self.dbwindow = QtWidgets.QDialog()
            self.ui =  Ui_DialogSat()
            self.ui.setupUi(self.dbwindow)
            self.dbwindow.show()

    def Reload(self):
            conn = sqlite3.connect("login.db")
            c = conn.cursor()
            c.execute("SELECT DISTINCT Sattelite FROM SAT")
            List = c.fetchall()
            conn.commit()
            conn.close()
            return List

    def ComboBoxCheck(self):
            satellite = self.SatelliteBox.currentText()

            conn = sqlite3.connect("login.db")
            cur = conn.cursor()
            # result = conn.execute("SELECT * FROM SAT")
            result = cur.execute("SELECT * FROM SAT WHERE Sattelite = ?", (satellite,))
            data = cur.fetchall()
            print("hello")
            for row in data:
                    print(row)
            self.TargetAzimuthText.clear()
            self.TargetElevationText.clear()
            self.TargetAzimuthText.insert(str(row[1]))
            self.TargetElevationText.insert(str(row[2]))
            conn.close()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("QDialog{\n"
"    \n"
"    background-image: url(:/newp/Icon/bg4.jpg)};")
        self.MPTMainLb = QtWidgets.QLabel(MainWindow)
        self.MPTMainLb.setGeometry(QtCore.QRect(200, 10, 251, 33))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.MPTMainLb.setFont(font)
        self.MPTMainLb.setStyleSheet("")
        self.MPTMainLb.setAlignment(QtCore.Qt.AlignCenter)
        self.MPTMainLb.setObjectName("MPTMainLb")
        self.widget = QtWidgets.QWidget(MainWindow)
        self.widget.setGeometry(QtCore.QRect(10, 60, 388, 313))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(20, 20, 20, 20)
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setVerticalSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        self.CurrentAzimuthLab = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CurrentAzimuthLab.sizePolicy().hasHeightForWidth())
        self.CurrentAzimuthLab.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.CurrentAzimuthLab.setFont(font)
        self.CurrentAzimuthLab.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.CurrentAzimuthLab.setObjectName("CurrentAzimuthLab")
        self.gridLayout.addWidget(self.CurrentAzimuthLab, 2, 1, 1, 1)
        self.TargetAzimuthLab = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TargetAzimuthLab.sizePolicy().hasHeightForWidth())
        self.TargetAzimuthLab.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.TargetAzimuthLab.setFont(font)
        self.TargetAzimuthLab.setAlignment(QtCore.Qt.AlignCenter)
        self.TargetAzimuthLab.setObjectName("TargetAzimuthLab")
        self.gridLayout.addWidget(self.TargetAzimuthLab, 2, 2, 1, 1)
        self.LONGText = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LONGText.sizePolicy().hasHeightForWidth())
        self.LONGText.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.LONGText.setFont(font)
        self.LONGText.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(205, 205, 205, 255), stop:1 rgba(255, 255, 255, 255));")
        self.LONGText.setAlignment(QtCore.Qt.AlignCenter)
        self.LONGText.setObjectName("LONGText")
        self.gridLayout.addWidget(self.LONGText, 10, 2, 1, 1)
        self.TargetAzimuthText = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TargetAzimuthText.sizePolicy().hasHeightForWidth())
        self.TargetAzimuthText.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.TargetAzimuthText.setFont(font)
        self.TargetAzimuthText.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(205, 205, 205, 255), stop:1 rgba(255, 255, 255, 255));")
        self.TargetAzimuthText.setAlignment(QtCore.Qt.AlignCenter)
        self.TargetAzimuthText.setObjectName("TargetAzimuthText")
        self.gridLayout.addWidget(self.TargetAzimuthText, 3, 2, 1, 1)
        self.CurrentElevationText = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CurrentElevationText.sizePolicy().hasHeightForWidth())
        self.CurrentElevationText.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.CurrentElevationText.setFont(font)
        self.CurrentElevationText.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(205, 205, 205, 255), stop:1 rgba(255, 255, 255, 255));")
        self.CurrentElevationText.setAlignment(QtCore.Qt.AlignCenter)
        self.CurrentElevationText.setObjectName("CurrentElevationText")
        self.gridLayout.addWidget(self.CurrentElevationText, 5, 1, 1, 1)
        self.LONGLab = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LONGLab.sizePolicy().hasHeightForWidth())
        self.LONGLab.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.LONGLab.setFont(font)
        self.LONGLab.setAlignment(QtCore.Qt.AlignCenter)
        self.LONGLab.setObjectName("LONGLab")
        self.gridLayout.addWidget(self.LONGLab, 9, 2, 1, 1)
        self.TargetElevationText = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TargetElevationText.sizePolicy().hasHeightForWidth())
        self.TargetElevationText.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.TargetElevationText.setFont(font)
        self.TargetElevationText.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(205, 205, 205, 255), stop:1 rgba(255, 255, 255, 255));")
        self.TargetElevationText.setAlignment(QtCore.Qt.AlignCenter)
        self.TargetElevationText.setObjectName("TargetElevationText")
        self.gridLayout.addWidget(self.TargetElevationText, 5, 2, 1, 1)
        self.TargetElevationLab = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TargetElevationLab.sizePolicy().hasHeightForWidth())
        self.TargetElevationLab.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.TargetElevationLab.setFont(font)
        self.TargetElevationLab.setAlignment(QtCore.Qt.AlignCenter)
        self.TargetElevationLab.setObjectName("TargetElevationLab")
        self.gridLayout.addWidget(self.TargetElevationLab, 4, 2, 1, 1)
        self.CurrentElevationLab = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CurrentElevationLab.sizePolicy().hasHeightForWidth())
        self.CurrentElevationLab.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.CurrentElevationLab.setFont(font)
        self.CurrentElevationLab.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.CurrentElevationLab.setObjectName("CurrentElevationLab")
        self.gridLayout.addWidget(self.CurrentElevationLab, 4, 1, 1, 1)
        self.CurrentAzimuthText = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CurrentAzimuthText.sizePolicy().hasHeightForWidth())
        self.CurrentAzimuthText.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.CurrentAzimuthText.setFont(font)
        self.CurrentAzimuthText.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(205, 205, 205, 255), stop:1 rgba(255, 255, 255, 255));")
        self.CurrentAzimuthText.setAlignment(QtCore.Qt.AlignCenter)
        self.CurrentAzimuthText.setObjectName("CurrentAzimuthText")
        self.gridLayout.addWidget(self.CurrentAzimuthText, 3, 1, 1, 1)
        self.CurrentPolarizationLab = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CurrentPolarizationLab.sizePolicy().hasHeightForWidth())
        self.CurrentPolarizationLab.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.CurrentPolarizationLab.setFont(font)
        self.CurrentPolarizationLab.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.CurrentPolarizationLab.setObjectName("CurrentPolarizationLab")
        self.gridLayout.addWidget(self.CurrentPolarizationLab, 9, 1, 1, 1)
        self.CurrentPolarizationText = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CurrentPolarizationText.sizePolicy().hasHeightForWidth())
        self.CurrentPolarizationText.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.CurrentPolarizationText.setFont(font)
        self.CurrentPolarizationText.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(205, 205, 205, 255), stop:1 rgba(255, 255, 255, 255));")
        self.CurrentPolarizationText.setAlignment(QtCore.Qt.AlignCenter)
        self.CurrentPolarizationText.setObjectName("CurrentPolarizationText")
        self.gridLayout.addWidget(self.CurrentPolarizationText, 10, 1, 1, 1)
        self.SignalStrengthLab = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SignalStrengthLab.sizePolicy().hasHeightForWidth())
        self.SignalStrengthLab.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.SignalStrengthLab.setFont(font)
        self.SignalStrengthLab.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.SignalStrengthLab.setObjectName("SignalStrengthLab")
        self.gridLayout.addWidget(self.SignalStrengthLab, 12, 1, 1, 1)
        self.LATLab = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.LATLab.setFont(font)
        self.LATLab.setAlignment(QtCore.Qt.AlignCenter)
        self.LATLab.setObjectName("LATLab")
        self.gridLayout.addWidget(self.LATLab, 12, 2, 1, 1)
        self.LATText = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LATText.sizePolicy().hasHeightForWidth())
        self.LATText.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.LATText.setFont(font)
        self.LATText.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(205, 205, 205, 255), stop:1 rgba(255, 255, 255, 255));")
        self.LATText.setAlignment(QtCore.Qt.AlignCenter)
        self.LATText.setObjectName("LATText")
        self.gridLayout.addWidget(self.LATText, 13, 2, 1, 1)
        self.SignalStrengthText = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SignalStrengthText.sizePolicy().hasHeightForWidth())
        self.SignalStrengthText.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.SignalStrengthText.setFont(font)
        self.SignalStrengthText.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(205, 205, 205, 255), stop:1 rgba(255, 255, 255, 255));")
        self.SignalStrengthText.setAlignment(QtCore.Qt.AlignCenter)
        self.SignalStrengthText.setObjectName("SignalStrengthText")
        self.gridLayout.addWidget(self.SignalStrengthText, 13, 1, 1, 1)
        self.widget1 = QtWidgets.QWidget(MainWindow)
        self.widget1.setGeometry(QtCore.QRect(382, 48, 221, 77))
        self.widget1.setObjectName("widget1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_3.setContentsMargins(20, 30, 20, 25)
        self.gridLayout_3.setSpacing(20)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.SatelliteBox = QtWidgets.QComboBox(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SatelliteBox.sizePolicy().hasHeightForWidth())
        self.SatelliteBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.SatelliteBox.setFont(font)
        self.SatelliteBox.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(205, 205, 205, 255), stop:1 rgba(255, 255, 255, 255));")
        self.SatelliteBox.setObjectName("SatelliteBox")
        self.gridLayout_3.addWidget(self.SatelliteBox, 0, 1, 1, 1)
        self.SatelliteLab = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SatelliteLab.sizePolicy().hasHeightForWidth())
        self.SatelliteLab.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.SatelliteLab.setFont(font)
        self.SatelliteLab.setObjectName("SatelliteLab")
        self.gridLayout_3.addWidget(self.SatelliteLab, 0, 0, 1, 1)
        self.widget2 = QtWidgets.QWidget(MainWindow)
        self.widget2.setGeometry(QtCore.QRect(382, 136, 219, 254))
        self.widget2.setObjectName("widget2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget2)
        self.gridLayout_2.setContentsMargins(20, 20, 20, 40)
        self.gridLayout_2.setHorizontalSpacing(5)
        self.gridLayout_2.setVerticalSpacing(30)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ControllerBut = QtWidgets.QPushButton(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ControllerBut.sizePolicy().hasHeightForWidth())
        self.ControllerBut.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.ControllerBut.setFont(font)
        self.ControllerBut.setMouseTracking(True)
        self.ControllerBut.setTabletTracking(True)
        self.ControllerBut.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"")
        self.ControllerBut.setAutoDefault(True)
        self.ControllerBut.setFlat(False)
        self.ControllerBut.setObjectName("ControllerBut")
        self.gridLayout_2.addWidget(self.ControllerBut, 0, 0, 1, 1)
        self.BUCTXBut = QtWidgets.QPushButton(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BUCTXBut.sizePolicy().hasHeightForWidth())
        self.BUCTXBut.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.BUCTXBut.setFont(font)
        self.BUCTXBut.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"")
        self.BUCTXBut.setObjectName("BUCTXBut")
        self.gridLayout_2.addWidget(self.BUCTXBut, 0, 1, 1, 1)
        self.CompassBut = QtWidgets.QPushButton(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CompassBut.sizePolicy().hasHeightForWidth())
        self.CompassBut.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.CompassBut.setFont(font)
        self.CompassBut.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"")
        self.CompassBut.setObjectName("CompassBut")
        self.gridLayout_2.addWidget(self.CompassBut, 1, 0, 1, 1)
        self.GPSBut_2 = QtWidgets.QPushButton(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GPSBut_2.sizePolicy().hasHeightForWidth())
        self.GPSBut_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.GPSBut_2.setFont(font)
        self.GPSBut_2.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.GPSBut_2.setObjectName("GPSBut_2")
        self.gridLayout_2.addWidget(self.GPSBut_2, 2, 1, 1, 1)
        self.ShutDownBut = QtWidgets.QPushButton(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ShutDownBut.sizePolicy().hasHeightForWidth())
        self.ShutDownBut.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.ShutDownBut.setFont(font)
        self.ShutDownBut.setMouseTracking(True)
        self.ShutDownBut.setTabletTracking(True)
        self.ShutDownBut.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"")
        self.ShutDownBut.setAutoDefault(True)
        self.ShutDownBut.setFlat(False)
        self.ShutDownBut.setObjectName("ShutDownBut")
        self.gridLayout_2.addWidget(self.ShutDownBut, 3, 0, 1, 1)
        self.BUCNABut = QtWidgets.QPushButton(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BUCNABut.sizePolicy().hasHeightForWidth())
        self.BUCNABut.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.BUCNABut.setFont(font)
        self.BUCNABut.setMouseTracking(True)
        self.BUCNABut.setTabletTracking(True)
        self.BUCNABut.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"")
        self.BUCNABut.setAutoDefault(True)
        self.BUCNABut.setFlat(False)
        self.BUCNABut.setObjectName("BUCNABut")
        self.gridLayout_2.addWidget(self.BUCNABut, 3, 1, 1, 1)
        self.GPSBut = QtWidgets.QPushButton(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GPSBut.sizePolicy().hasHeightForWidth())
        self.GPSBut.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.GPSBut.setFont(font)
        self.GPSBut.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.GPSBut.setObjectName("GPSBut")
        self.gridLayout_2.addWidget(self.GPSBut, 1, 1, 1, 1)
        self.CompassBut_2 = QtWidgets.QPushButton(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CompassBut_2.sizePolicy().hasHeightForWidth())
        self.CompassBut_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.CompassBut_2.setFont(font)
        self.CompassBut_2.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"")
        self.CompassBut_2.setObjectName("CompassBut_2")
        self.gridLayout_2.addWidget(self.CompassBut_2, 2, 0, 1, 1)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.ShutDownBut.clicked.connect(self.ShutDownCheck)

        self.CompassBut.clicked.connect(self.SerialDataCheck)

        #self.GPSBut.clicked.connect(self.ThreadStop)

        self.SatelliteBox.activated[str].connect(self.ComboBoxCheck)

        self.SatelliteBox.addItem(" ")
        #self.SatelliteBox.addItems(['GSAT-8', 'SAT-1', 'SAT-2', 'SAT-3', 'SAT-4'])
        lst = self.Reload()
        y = str(lst)
        print(y)

        x = [str(i).strip("'()',") for i in lst]
        self.SatelliteBox.addItems(x)

        #for i in range(len(lst)):
                #lst[i] = str(lst[i])
                #self.SatelliteBox.addItems("lst[i}")

                #print(lst[i])





        self.CompassBut_2.clicked.connect(self.opendb)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MPT Main"))
        MainWindow.setWindowFlags(MainWindow.windowFlags() |
                                  QtCore.Qt.WindowSystemMenuHint |
                                  QtCore.Qt.WindowMinMaxButtonsHint)
        MainWindow.setWindowIcon(QtGui.QIcon('C:\\Users\\MAHE\\Desktop\\MPTgui\\Icon\\icon1.jpg'))
        self.MPTMainLb.setText(_translate("MainWindow", "<html><head/><body><p>MPT Main Window</p></body></html>"))
        self.CurrentAzimuthLab.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#000000;\">Current Azimuth</span></p></body></html>"))
        self.TargetAzimuthLab.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#000000;\">Target Azimuth</span></p></body></html>"))
        self.TargetAzimuthText.setText(_translate("MainWindow", "34"))
        self.LONGLab.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#000000;\">LONG (S)</span></p></body></html>"))
        self.TargetElevationLab.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#000000;\">Target Elevation</span></p></body></html>"))
        self.CurrentElevationLab.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#000000;\">Current Elevation</span></p></body></html>"))
        self.CurrentPolarizationLab.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Current Polarization</span></p></body></html>"))
        self.SignalStrengthLab.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#000000;\">Signal Strength (dBm)</span></p></body></html>"))
        self.LATLab.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#000000;\">LAT (N)</span></p></body></html>"))
        self.SatelliteLab.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#000000;\">Satellite</span></p></body></html>"))
        self.ControllerBut.setText(_translate("MainWindow", "Controller"))
        self.BUCTXBut.setText(_translate("MainWindow", "BUC TX"))
        self.CompassBut.setText(_translate("MainWindow", "Compass"))
        self.GPSBut_2.setText(_translate("MainWindow", "Get"))
        self.ShutDownBut.setText(_translate("MainWindow", "SHUTDOWN"))
        self.BUCNABut.setText(_translate("MainWindow", "BUC NA"))
        self.GPSBut.setText(_translate("MainWindow", "GPS"))
        self.CompassBut_2.setText(_translate("MainWindow", "Database"))

import resource_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QDialog()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())


