import sys
import resource_rc
sys._excepthook = sys.excepthook
def my_exception_hook(exctype, value, traceback):
    print(exctype, value, traceback)
    sys._excepthook(exctype, value, traceback)
    sys.exit(1)
sys.excepthook = my_exception_hook


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
import sqlite3
import sys
from MPTSignUp3 import  Ui_signUp
from MPTgui3 import Ui_MainWindow

class Ui_Dialog(object):
    def Button_Pressed(self):
        button = Dialog.sender()


        self.UserIDSutxt.setFocusPolicy(Qt.StrongFocus)

        newtext = format(float(self.UserIDSutxt.text() + button.text()),'.15g')
        self.UserIDSutxt.setText(newtext)
        self.PasswordSutxt.setText(newtext)

    def SignUpCheck(self):
        print("to the signUp tab")
        self.signUpShow()

    def loginCheck(self):
        print("login clicked")
        userID = self.UserIDSutxt.text()
        password = self.PasswordSutxt.text()

        conn = sqlite3.connect("login.db")
        result = conn.execute("SELECT * FROM USERS WHERE USERID = ? AND PASSWORD = ?", (userID, password))
        if len(result.fetchall()) > 0:
            print("user found !")
            self.welcomewindowshow()
        else:
            print("user not found !")
            self.showMessageBox('Warning', 'Invalid Username Or Password')
        conn.close()

    def signUpShow(self):
        self.signUpWindow = QtWidgets.QDialog()
        self.ui = Ui_signUp()
        self.ui.setupUi(self.signUpWindow)
        self.signUpWindow.show()
        Dialog.close()

    def welcomewindowshow(self):
        self.welcomeWindow = QtWidgets.QDialog()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.welcomeWindow)
        self.welcomeWindow.show()
        Dialog.close()

    def showMessageBox(self,title,message):
        msgBox = QtWidgets.QMessageBox()
        msgBox.setIcon(QtWidgets.QMessageBox.Warning)
        msgBox.setWindowTitle(title)
        msgBox.setWindowIcon(QtGui.QIcon('C:\\Users\\MAHE\\Desktop\\MPTgui\\Icon\\icon1.jpg'))
        msgBox.setText(message)
        msgBox.setStandardButtons(QtWidgets.QMessageBox.Ok)
        msgBox.exec_()

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(600, 400)
        Dialog.setStyleSheet("QDialog{background-image: url(:/newp/Icon/bg2.jpg)};")
        #Dialog.setStyleSheet("QDialog{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(37, 140, 140, 255), stop:1 rgba(255, 255, 255, 255))};")
        self.gridLayout_3 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(20, 20, 20, 20)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 1, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 1, 2, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 1, 1, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 2, 1, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 2, 0, 1, 1)
        self.pushButton_0 = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_0.sizePolicy().hasHeightForWidth())
        self.pushButton_0.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_0.setFont(font)
        self.pushButton_0.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.pushButton_0.setObjectName("pushButton_0")
        self.gridLayout.addWidget(self.pushButton_0, 3, 1, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 2, 2, 1, 1)
        self.pushButton_has = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_has.sizePolicy().hasHeightForWidth())
        self.pushButton_has.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_has.setFont(font)
        self.pushButton_has.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.pushButton_has.setObjectName("pushButton_has")
        self.gridLayout.addWidget(self.pushButton_has, 3, 0, 1, 1)
        self.pushButton_amp = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_amp.sizePolicy().hasHeightForWidth())
        self.pushButton_amp.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_amp.setFont(font)
        self.pushButton_amp.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.pushButton_amp.setObjectName("pushButton_amp")
        self.gridLayout.addWidget(self.pushButton_amp, 3, 2, 1, 1)
        self.pushButton_1 = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_1.sizePolicy().hasHeightForWidth())
        self.pushButton_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.pushButton_1.setObjectName("pushButton_1")
        self.gridLayout.addWidget(self.pushButton_1, 0, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 0, 2, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 3, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_2.setHorizontalSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.SignUpLgBut = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SignUpLgBut.sizePolicy().hasHeightForWidth())
        self.SignUpLgBut.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.SignUpLgBut.setFont(font)
        self.SignUpLgBut.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.SignUpLgBut.setObjectName("SignUpLgBut")
        self.gridLayout_2.addWidget(self.SignUpLgBut, 0, 0, 1, 1)
        self.LoginBut = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LoginBut.sizePolicy().hasHeightForWidth())
        self.LoginBut.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.LoginBut.setFont(font)
        self.LoginBut.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.LoginBut.setObjectName("LoginBut")
        self.gridLayout_2.addWidget(self.LoginBut, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 2, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout.setRowWrapPolicy(QtWidgets.QFormLayout.WrapLongRows)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setObjectName("formLayout")
        self.UserIDlbSu = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.UserIDlbSu.setFont(font)
        self.UserIDlbSu.setAlignment(QtCore.Qt.AlignCenter)
        self.UserIDlbSu.setObjectName("UserIDlbSu")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.UserIDlbSu)
        self.UserIDSutxt = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UserIDSutxt.sizePolicy().hasHeightForWidth())
        self.UserIDSutxt.setSizePolicy(sizePolicy)
        self.UserIDSutxt.setObjectName("UserIDSutxt")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.UserIDSutxt)
        self.PasswordSu = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.PasswordSu.setFont(font)
        self.PasswordSu.setAlignment(QtCore.Qt.AlignCenter)
        self.PasswordSu.setObjectName("PasswordSu")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.PasswordSu)
        self.PasswordSutxt = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PasswordSutxt.sizePolicy().hasHeightForWidth())
        self.PasswordSutxt.setSizePolicy(sizePolicy)
        self.PasswordSutxt.setObjectName("PasswordSutxt")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.PasswordSutxt)
        self.gridLayout_3.addLayout(self.formLayout, 1, 0, 1, 1)
        self.MPTlglb = QtWidgets.QLabel(Dialog)
        self.MPTlglb.setAlignment(QtCore.Qt.AlignCenter)
        self.MPTlglb.setObjectName("MPTlglb")
        self.gridLayout_3.addWidget(self.MPTlglb, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.LoginBut.clicked.connect(self.loginCheck)
        self.SignUpLgBut.clicked.connect(self.SignUpCheck)
        self.PasswordSutxt.setEchoMode(QtWidgets.QLineEdit.Password)
        self.PasswordSutxt.show()

        self.pushButton_1.clicked.connect(self.Button_Pressed)
        self.pushButton_2.clicked.connect(self.Button_Pressed)
        self.pushButton_3.clicked.connect(self.Button_Pressed)
        self.pushButton_4.clicked.connect(self.Button_Pressed)
        self.pushButton_5.clicked.connect(self.Button_Pressed)
        self.pushButton_6.clicked.connect(self.Button_Pressed)
        self.pushButton_7.clicked.connect(self.Button_Pressed)
        self.pushButton_8.clicked.connect(self.Button_Pressed)
        self.pushButton_9.clicked.connect(self.Button_Pressed)
        self.pushButton_0.clicked.connect(self.Button_Pressed)



    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Login"))
        Dialog.setWindowFlags(Dialog.windowFlags() |
                              QtCore.Qt.WindowSystemMenuHint |
                              QtCore.Qt.WindowMinMaxButtonsHint)
        self.pushButton_4.setText(_translate("Dialog", "4"))
        self.pushButton_6.setText(_translate("Dialog", "6"))
        self.pushButton_5.setText(_translate("Dialog", "5"))
        self.pushButton_8.setText(_translate("Dialog", "8"))
        self.pushButton_7.setText(_translate("Dialog", "7"))
        self.pushButton_0.setText(_translate("Dialog", "0"))
        self.pushButton_9.setText(_translate("Dialog", "9"))
        self.pushButton_has.setText(_translate("Dialog", "#"))
        self.pushButton_amp.setText(_translate("Dialog", "%"))
        self.pushButton_1.setText(_translate("Dialog", "1"))
        self.pushButton_3.setText(_translate("Dialog", "3"))
        self.pushButton_2.setText(_translate("Dialog", "2"))
        self.SignUpLgBut.setText(_translate("Dialog", "Sign Up"))
        self.LoginBut.setText(_translate("Dialog", "Login"))
        self.UserIDlbSu.setText(_translate("Dialog", "USER ID"))
        self.PasswordSu.setText(_translate("Dialog", "PASSWORD"))

        Dialog.setWindowIcon(QtGui.QIcon('C:\\Users\\MAHE\\Desktop\\MPTgui\\Icon\\icon1.jpg'))
        #Dialog.setStyleSheet("QDialog{background-image: url(C:/Users/MAHE/Desktop/MPTgui/Icon/bg2.jpg)};")
        self.MPTlglb.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600;\">MPT LOGIN</span></p></body></html>"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    ui.UserIDSutxt.setFocus()
    sys.exit(app.exec_())


